### ISSUE TITLE
Minimum lenght requirement not met

### ISSUE THREAD

**Issue by joshdmwood** [suryasr007/random-password-generator#149]
i noticed when attempting to use the API hosted on heroku that the passwords don't match the minimum lenght of characters that I'm giving. I have verified the arguments and they match, but I can't seem to have a constant 16 character string, see the link below:
`https://random-pg.herokuapp.com/api/generate?minlen=16&maxlen=16&minuchars=2&minlchars=2&minnumbers=2&minschars=2`

and some results:
```json
{"password":"Ek.lf0EOv"}
{"password":"pqWTi5%3&,2.Kt,"}
{"password":"rZPp%BHS7x1QB"}
{"password":"LOyr4qwgX$Csms<G"}
{"password":"a$WJI2"}
{"password":"3A5vqRP^s+d"}
{"password":"Jxz,wkFxb^6"}
```

**Comment by suryasr007** [comment]
Will be fixed as part https://github.com/suryasr007/random-password-generator/pull/150.
