### ISSUE TITLE
Change 'random' lib for 'secrets'

### ISSUE THREAD

**Issue by urielfcampos** [suryasr007/random-password-generator#34]
As this is generating passwords, the documentation for [random](https://docs.python.org/3/library/random.html) suggests not using it for security and etc, instead they suggest using the [secrets](https://docs.python.org/3/library/secrets.html#module-secrets) module for that. 
What do you think ?

**Comment by suryasr007** [comment]
I have already changed that but not pushed to master yet.

[dev](https://github.com/suryasr007/random-password-generator/blob/dev/password_generator.py)

There is still a slight problem, secrets module is not supported on python < 3.6. Hence I need to make it hybrid (yet it is better than using only the random module).
