### ISSUE TITLE
Errors/Incorrect generation when the filters value is zero "0"

### ISSUE THREAD

**Issue by suryasr007** [suryasr007/random-password-generator#89]
![image](https://user-images.githubusercontent.com/10533926/73719275-ebf0da80-4744-11ea-84bf-3ea7b303ed7c.png)

To Reproduce:
 * Open the App.
 * Change the value of any filter to zero "0" and click generate.
 * The value is not generated or the generated value is correct.

**Comment by bronte2k7** [comment]
When will the release be?

**Comment by suryasr007** [comment]
Fixed.
